blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Support
    url: https://github.com/Jellyforge-Dev/Questorr/discussions
    about: For questions and general support, please use Discussions instead of Issues.
  - name: 🤝 Join our Discord
    url: https://discord.gg/J9V9ySZQKf
    about: Chat with the community and get help on our Discord server.
