/**
 * Bot-side translation helper.
 * Reads BOT_LANGUAGE (or LANGUAGE) from environment. Supports "en" and "de".
 */

const strings = {
  en: {
    event_pending:        "New Request \u2013 Pending Approval",
    event_approved:       "Request Approved",
    event_auto_approved:  "Request Auto-Approved",
    event_available:      "Now Available!",
    event_declined:       "Request Declined",
    event_failed:         "Download Failed",
    event_issue_created:  "Issue Reported",
    event_issue_comment:  "Issue Comment",
    event_issue_resolved: "Issue Resolved",
    event_issue_reopened: "Issue Reopened",
    event_test:           "Test Notification",
    field_requested_by:   "Requested by",
    field_type:           "Type",
    field_type_movie:     "\uD83C\uDFAC Movie",
    field_type_tv:        "\uD83D\uDCFA TV Show",
    field_reason:         "Reason",
    field_rating:         "Rating",
    btn_view_seerr:       "View on Seerr",
    btn_watch_now:        "\u25B6 Watch Now!",
    btn_imdb:             "IMDb",
    btn_letterboxd:       "Letterboxd",
    btn_request:          "\uD83D\uDCE5 Request",
    btn_watch_now_short:  "\u25B6 Watch Now",
    daily_random_pick:    "Today\u2019s Random Pick",
    daily_recommendation: "\uD83C\uDFAC Today\u2019s Recommendation on Jellyfin",
    status_unknown:       "Unknown",
    status_pending:       "Pending Approval",
    status_processing:    "Processing / Downloading",
    status_partial:       "Partially Available",
    status_available:     "Available",
    status_deleted:       "Deleted",
    status_pending_short: "Pending",
    status_not_requested: "This title has not been requested yet.",
    successfully_requested: "\u2705 Successfully requested!",
    requested_label:      "Requested",
    requested_all_seasons:"Requested all seasons",
    requested_season:     "Requested season",
    requested_seasons:    "Requested seasons",
    request_all_seasons:  "Request all seasons",
    request_season:       "Request season",
    request_seasons:      "Request seasons",
    all_seasons:          "All Seasons",
    season_label:         "Season",
    episodes_label:       "episodes",
    stay_tuned:           "stay tuned!",
    random_movie:         "Random Movie",
    random_series:        "Random Series",
    title_invalid:        "\u26A0\uFE0F The title seems to be invalid.",
    content_already_available: "\u2705 This content is already available in your library!",
    error_occurred:       "\u26A0\uFE0F An error occurred.",
    error_seerr:          "\u26A0\uFE0F Seerr error: {{message}}",
    error_quota:          "\u26A0\uFE0F Request failed: You might have exceeded your quota or don\u2019t have permission.",
    error_generic:        "\u26A0\uFE0F Error: {{message}}",
    error_request_failed: "\u26A0\uFE0F I could not send the request.",
    error_season_select:  "\u26A0\uFE0F Error processing season selection.",
    error_tag_select:     "\u26A0\uFE0F Error updating selection.",
    select_tags_placeholder: "Select tags (optional)",
    select_seasons_placeholder: "Select seasons to request...",
    status_disabled:      "\u26A0\uFE0F The /status command is currently disabled.",
    status_select_title:  "\u274C Please select a title from the dropdown suggestions.",
    status_seerr_missing: "\u274C Seerr is not configured.",
    status_fetch_error:   "\u274C Could not fetch status from Seerr. Please try again.",
    random_disabled:      "\u26A0\uFE0F The /random command is currently disabled.",
    random_jf_missing:    "\u274C Jellyfin is not configured.",
    random_not_found:     "\u274C No {{type}} found in your Jellyfin library.",
    random_fetch_error:   "\u274C Could not fetch a random title. Please try again.",
    command_config_missing: "\u26A0\uFE0F This command is disabled because Seerr or TMDB configuration is missing.",
    no_permission:        "\u274C You don\u2019t have permission to use this command.",
    id_invalid:           "\u26A0\uFE0F ID invalid.",
    invalid_selection:    "\u26A0\uFE0F Invalid selection.",
    invalid_request:      "\u26A0\uFE0F Invalid request.",
    invalid_request_data: "\u26A0\uFE0F Invalid request data.",
    already_requested:    "This item was already requested.",
    invalid_media_id:     "\u26A0\uFE0F Invalid media ID.",
    error_processing:     "\u26A0\uFE0F Error processing request.",
    request_success:      "\u2705 **{{title}}** has been requested!",
    label_genre:          "Genre",
    label_runtime:        "Runtime",
    label_rating:         "Rating",
    label_age_rating:     "Age Rating",
    no_description:       "No description available.",
    label_summary:        "Summary",
    label_directed_by:    "Directed by {{name}}",
    label_created_by:     "Created by {{name}}",
    movie_found:          "\uD83C\uDFAC Movie found:",
    tv_found:             "\uD83D\uDCFA TV show found:",
    and_connector:        "and",
    with_tag:             "with {{tags}} tag",
    with_tags:            "with {{tags}} tags",
    rate_limited:         "\u26A0\uFE0F You're using commands too fast. Please wait a moment.",
    btn_approve:          "\u2705 Approve",
    btn_decline:          "\u274C Decline",
    btn_approved_by:      "Approved by",
    btn_declined_by:      "Declined by",
    watchlist_title:       "\uD83D\uDCCB Request Watchlist",
    watchlist_empty:       "No requests found.",
    watchlist_no_mapping:  "\u26A0\uFE0F Your Discord account is not mapped to a Seerr user. Ask an admin to set up your user mapping.",
    watchlist_error:       "\u274C Could not fetch requests from Seerr.",
    watchlist_showing:     "Showing {{shown}} of {{total}} requests",
    upcoming_title:        "\uD83D\uDCC5 Upcoming Releases",
    upcoming_empty:        "No upcoming releases found.",
    upcoming_error:        "\u274C Could not fetch upcoming releases from TMDB.",
    history_title:         "\uD83D\uDCDA Recently Added",
    history_empty:         "No recently added content found on Jellyfin.",
    history_jf_missing:    "\u274C Jellyfin is not configured.",
    history_error:         "\u274C Could not fetch recently added content from Jellyfin.",
    recommend_title:       "\uD83C\uDFAF Recommendations",
    recommend_based_on:    "Based on \"{{title}}\"",
    recommend_not_found:   "\u274C Could not find this title on TMDB.",
    recommend_no_similar:  "\u274C No recommendations found for \"{{title}}\".",
    recommend_error:       "\u274C Could not fetch recommendations. Please try again.",
    recommend_legend:      "\u2705 = Available on Jellyfin \u00B7 \u274C = Not available",
    btn_trailer:           "\u25B6 Trailer",
    discover_title:        "\uD83D\uDD0D Discover",
    discover_empty:        "\u274C No results found for your filters.",
    discover_error:        "\u274C Could not fetch results. Please try again.",
    discover_all:          "All",
    collection_title:      "\uD83D\uDCDA Collection",
    collection_not_found:  "\u274C Could not find this title on TMDB.",
    collection_movies_only:"\u26A0\uFE0F Collections are only available for movies.",
    collection_none:       "\u274C This movie is not part of a collection.",
    collection_error:      "\u274C Could not fetch collection. Please try again.",
    collection_available:  "in your library",
    cast_title:            "\uD83C\uDFAD Filmography",
    cast_name_required:    "\u26A0\uFE0F Please enter an actor or actress name.",
    cast_not_found:        "\u274C Could not find this person on TMDB.",
    cast_no_credits:       "\u274C No movie or TV credits found for this person.",
    cast_error:            "\u274C Could not fetch filmography. Please try again.",
  },
  de: {
    event_pending:        "Neue Anfrage \u2013 Ausstehend",
    event_approved:       "Anfrage genehmigt",
    event_auto_approved:  "Anfrage automatisch genehmigt",
    event_available:      "Jetzt verf\u00FCgbar!",
    event_declined:       "Anfrage abgelehnt",
    event_failed:         "Download fehlgeschlagen",
    event_issue_created:  "Problem gemeldet",
    event_issue_comment:  "Problem-Kommentar",
    event_issue_resolved: "Problem gel\u00F6st",
    event_issue_reopened: "Problem wieder ge\u00F6ffnet",
    event_test:           "Test-Benachrichtigung",
    field_requested_by:   "Angefragt von",
    field_type:           "Typ",
    field_type_movie:     "\uD83C\uDFAC Film",
    field_type_tv:        "\uD83D\uDCFA Serie",
    field_reason:         "Grund",
    field_rating:         "Bewertung",
    btn_view_seerr:       "In Seerr ansehen",
    btn_watch_now:        "\u25B6 Jetzt ansehen!",
    btn_imdb:             "IMDb",
    btn_letterboxd:       "Letterboxd",
    btn_request:          "\uD83D\uDCE5 Anfragen",
    btn_watch_now_short:  "\u25B6 Jetzt ansehen",
    daily_random_pick:    "Heutiger Zufallstitel",
    daily_recommendation: "\uD83C\uDFAC Heutige Empfehlung auf Jellyfin",
    status_unknown:       "Unbekannt",
    status_pending:       "Ausstehend",
    status_processing:    "Wird verarbeitet / heruntergeladen",
    status_partial:       "Teilweise verf\u00FCgbar",
    status_available:     "Verf\u00FCgbar",
    status_deleted:       "Gel\u00F6scht",
    status_pending_short: "Ausstehend",
    status_not_requested: "Dieser Titel wurde noch nicht angefragt.",
    successfully_requested: "\u2705 Erfolgreich angefragt!",
    requested_label:      "Angefragt",
    requested_all_seasons:"Alle Staffeln angefragt",
    requested_season:     "Staffel angefragt",
    requested_seasons:    "Staffeln angefragt",
    request_all_seasons:  "Alle Staffeln anfragen",
    request_season:       "Staffel anfragen",
    request_seasons:      "Staffeln anfragen",
    all_seasons:          "Alle Staffeln",
    season_label:         "Staffel",
    episodes_label:       "Episoden",
    stay_tuned:           "bleibt gespannt!",
    random_movie:         "Zuf\u00E4lliger Film",
    random_series:        "Zuf\u00E4llige Serie",
    title_invalid:        "\u26A0\uFE0F Der Titel scheint ung\u00FCltig zu sein.",
    content_already_available: "\u2705 Dieser Inhalt ist bereits in deiner Bibliothek verf\u00FCgbar!",
    error_occurred:       "\u26A0\uFE0F Ein Fehler ist aufgetreten.",
    error_seerr:          "\u26A0\uFE0F Seerr-Fehler: {{message}}",
    error_quota:          "\u26A0\uFE0F Anfrage fehlgeschlagen: M\u00F6glicherweise wurde dein Kontingent \u00FCberschritten oder dir fehlt die Berechtigung.",
    error_generic:        "\u26A0\uFE0F Fehler: {{message}}",
    error_request_failed: "\u26A0\uFE0F Die Anfrage konnte nicht gesendet werden.",
    error_season_select:  "\u26A0\uFE0F Fehler bei der Staffelauswahl.",
    error_tag_select:     "\u26A0\uFE0F Fehler beim Aktualisieren der Auswahl.",
    select_tags_placeholder: "Tags ausw\u00E4hlen (optional)",
    select_seasons_placeholder: "Staffeln zum Anfragen ausw\u00E4hlen...",
    status_disabled:      "\u26A0\uFE0F Der /status-Befehl ist derzeit deaktiviert.",
    status_select_title:  "\u274C Bitte w\u00E4hle einen Titel aus den Vorschl\u00E4gen.",
    status_seerr_missing: "\u274C Seerr ist nicht konfiguriert.",
    status_fetch_error:   "\u274C Status konnte nicht von Seerr abgerufen werden. Bitte versuche es erneut.",
    random_disabled:      "\u26A0\uFE0F Der /random-Befehl ist derzeit deaktiviert.",
    random_jf_missing:    "\u274C Jellyfin ist nicht konfiguriert.",
    random_not_found:     "\u274C Kein {{type}} in deiner Jellyfin-Bibliothek gefunden.",
    random_fetch_error:   "\u274C Zuf\u00E4lliger Titel konnte nicht abgerufen werden. Bitte versuche es erneut.",
    command_config_missing: "\u26A0\uFE0F Dieser Befehl ist deaktiviert, da die Seerr- oder TMDB-Konfiguration fehlt.",
    no_permission:        "\u274C Du hast keine Berechtigung, diesen Befehl zu verwenden.",
    id_invalid:           "\u26A0\uFE0F ID ung\u00FCltig.",
    invalid_selection:    "\u26A0\uFE0F Ung\u00FCltige Auswahl.",
    invalid_request:      "\u26A0\uFE0F Ung\u00FCltige Anfrage.",
    invalid_request_data: "\u26A0\uFE0F Ung\u00FCltige Anfragedaten.",
    already_requested:    "Dieser Titel wurde bereits angefragt.",
    invalid_media_id:     "\u26A0\uFE0F Ung\u00FCltige Medien-ID.",
    error_processing:     "\u26A0\uFE0F Fehler bei der Verarbeitung der Anfrage.",
    request_success:      "\u2705 **{{title}}** wurde angefragt!",
    label_genre:          "Genre",
    label_runtime:        "Laufzeit",
    label_rating:         "Bewertung",
    label_age_rating:     "Altersfreigabe",
    no_description:       "Keine Beschreibung verf\u00FCgbar.",
    label_summary:        "Zusammenfassung",
    label_directed_by:    "Regie: {{name}}",
    label_created_by:     "Erstellt von {{name}}",
    movie_found:          "\uD83C\uDFAC Film gefunden:",
    tv_found:             "\uD83D\uDCFA Serie gefunden:",
    and_connector:        "und",
    with_tag:             "mit Tag {{tags}}",
    with_tags:            "mit Tags {{tags}}",
    rate_limited:         "\u26A0\uFE0F Du verwendest Befehle zu schnell. Bitte warte einen Moment.",
    btn_approve:          "\u2705 Genehmigen",
    btn_decline:          "\u274C Ablehnen",
    btn_approved_by:      "Genehmigt von",
    btn_declined_by:      "Abgelehnt von",
    watchlist_title:       "\uD83D\uDCCB Anfragen-Liste",
    watchlist_empty:       "Keine Anfragen gefunden.",
    watchlist_no_mapping:  "\u26A0\uFE0F Dein Discord-Konto ist keinem Seerr-Benutzer zugeordnet. Bitte einen Admin, dein User-Mapping einzurichten.",
    watchlist_error:       "\u274C Anfragen konnten nicht von Seerr abgerufen werden.",
    watchlist_showing:     "Zeige {{shown}} von {{total}} Anfragen",
    upcoming_title:        "\uD83D\uDCC5 Kommende Ver\u00F6ffentlichungen",
    upcoming_empty:        "Keine kommenden Ver\u00F6ffentlichungen gefunden.",
    upcoming_error:        "\u274C Kommende Ver\u00F6ffentlichungen konnten nicht von TMDB abgerufen werden.",
    history_title:         "\uD83D\uDCDA Kürzlich hinzugefügt",
    history_empty:         "Keine kürzlich hinzugefügten Inhalte auf Jellyfin gefunden.",
    history_jf_missing:    "\u274C Jellyfin ist nicht konfiguriert.",
    history_error:         "\u274C Kürzlich hinzugefügte Inhalte konnten nicht von Jellyfin abgerufen werden.",
    recommend_title:       "\uD83C\uDFAF Empfehlungen",
    recommend_based_on:    "Basierend auf \"{{title}}\"",
    recommend_not_found:   "\u274C Dieser Titel konnte nicht auf TMDB gefunden werden.",
    recommend_no_similar:  "\u274C Keine Empfehlungen f\u00FCr \"{{title}}\" gefunden.",
    recommend_error:       "\u274C Empfehlungen konnten nicht abgerufen werden. Bitte versuche es erneut.",
    recommend_legend:      "\u2705 = Auf Jellyfin verf\u00FCgbar \u00B7 \u274C = Nicht verf\u00FCgbar",
    btn_trailer:           "\u25B6 Trailer",
    discover_title:        "\uD83D\uDD0D Entdecken",
    discover_empty:        "\u274C Keine Ergebnisse f\u00FCr deine Filter gefunden.",
    discover_error:        "\u274C Ergebnisse konnten nicht abgerufen werden. Bitte versuche es erneut.",
    discover_all:          "Alle",
    collection_title:      "\uD83D\uDCDA Sammlung",
    collection_not_found:  "\u274C Dieser Titel konnte nicht auf TMDB gefunden werden.",
    collection_movies_only:"\u26A0\uFE0F Sammlungen sind nur f\u00FCr Filme verf\u00FCgbar.",
    collection_none:       "\u274C Dieser Film geh\u00F6rt zu keiner Sammlung.",
    collection_error:      "\u274C Sammlung konnte nicht abgerufen werden. Bitte versuche es erneut.",
    collection_available:  "in deiner Bibliothek",
    cast_title:            "\uD83C\uDFAD Filmografie",
    cast_name_required:    "\u26A0\uFE0F Bitte gib einen Schauspieler-Namen ein.",
    cast_not_found:        "\u274C Diese Person konnte nicht auf TMDB gefunden werden.",
    cast_no_credits:       "\u274C Keine Film- oder Serien-Credits f\u00FCr diese Person gefunden.",
    cast_error:            "\u274C Filmografie konnte nicht abgerufen werden. Bitte versuche es erneut.",
  },
};

export function t(key) {
  const lang = (process.env.BOT_LANGUAGE || "en").toLowerCase();
  const dict = strings[lang] || strings["en"];
  return dict[key] ?? strings["en"][key] ?? key;
}

export function tNotif(key, envKey) {
  const custom = process.env[envKey];
  if (custom && custom.trim()) return custom.trim();
  return t(key);
}

export default { t, tNotif };
