/**
 * Bot-side translation helper.
 * Reads BOT_LANGUAGE (or LANGUAGE) from environment. Supports "en" and "de".
 */

const strings = {
  en: {
    event_pending:        "New Request \u2013 Pending Approval",
    event_approved:       "Request Approved",
    event_auto_approved:  "Request Auto-Approved",
    event_available:      "Now Available!",
    event_declined:       "Request Declined",
    event_failed:         "Download Failed",
    event_issue_created:  "Issue Reported",
    event_issue_comment:  "Issue Comment",
    event_issue_resolved: "Issue Resolved",
    event_issue_reopened: "Issue Reopened",
    event_test:           "Test Notification",
    field_requested_by:   "Requested by",
    requested_by:         "Requested by {{user}}",
    field_type:           "Type",
    field_type_movie:     "\uD83C\uDFAC Movie",
    field_type_tv:        "\uD83D\uDCFA TV Show",
    field_reason:         "Reason",
    field_rating:         "Rating",
    btn_view_seerr:       "View on Seerr",
    btn_watch_now:        "\u25B6 Watch Now!",
    btn_imdb:             "IMDb",
    btn_letterboxd:       "Letterboxd",
    btn_request:          "\uD83D\uDCE5 Request",
    btn_watch_now_short:  "\u25B6 Watch Now",
    daily_random_pick:    "Today\u2019s Random Pick",
    daily_recommendation: "\uD83C\uDFAC Today\u2019s Recommendation on Jellyfin",
    status_unknown:       "Unknown",
    status_pending:       "Pending Approval",
    status_processing:    "Processing / Downloading",
    status_partial:       "Partially Available",
    status_available:     "Available",
    status_deleted:       "Deleted",
    status_pending_short: "Pending",
    status_not_requested: "This title has not been requested yet.",
    successfully_requested: "\u2705 Successfully requested!",
    requested_label:      "Requested",
    requested_all_seasons:"Requested all seasons",
    requested_season:     "Requested season",
    requested_seasons:    "Requested seasons",
    request_all_seasons:  "Request all seasons",
    request_season:       "Request season",
    request_seasons:      "Request seasons",
    all_seasons:          "All Seasons",
    season_label:         "Season",
    episodes_label:       "episodes",
    stay_tuned:           "stay tuned!",
    random_movie:         "Random Movie",
    random_series:        "Random Series",
    title_invalid:        "\u26A0\uFE0F The title seems to be invalid.",
    content_already_available: "\u2705 This content is already available in your library!",
    error_occurred:       "\u26A0\uFE0F An error occurred.",
    error_seerr:          "\u26A0\uFE0F Seerr error: {{message}}",
    error_quota:          "\u26A0\uFE0F Request failed: You might have exceeded your quota or don\u2019t have permission.",
    error_generic:        "\u26A0\uFE0F Error: {{message}}",
    error_request_failed: "\u26A0\uFE0F I could not send the request.",
    error_season_select:  "\u26A0\uFE0F Error processing season selection.",
    error_tag_select:     "\u26A0\uFE0F Error updating selection.",
    select_tags_placeholder: "Select tags (optional)",
    select_seasons_placeholder: "Select seasons to request...",
    status_disabled:      "\u26A0\uFE0F The /status command is currently disabled.",
    status_select_title:  "\u274C Please select a title from the dropdown suggestions.",
    status_seerr_missing: "\u274C Seerr is not configured.",
    status_fetch_error:   "\u274C Could not fetch status from Seerr. Please try again.",
    random_disabled:      "\u26A0\uFE0F The /random command is currently disabled.",
    random_jf_missing:    "\u274C Jellyfin is not configured.",
    random_not_found:     "\u274C No {{type}} found in your Jellyfin library.",
    random_fetch_error:   "\u274C Could not fetch a random title. Please try again.",
    command_config_missing: "\u26A0\uFE0F This command is disabled because Seerr or TMDB configuration is missing.",
    no_permission:        "\u274C You don\u2019t have permission to use this command.",
    id_invalid:           "\u26A0\uFE0F ID invalid.",
    invalid_selection:    "\u26A0\uFE0F Invalid selection.",
    invalid_request:      "\u26A0\uFE0F Invalid request.",
    invalid_request_data: "\u26A0\uFE0F Invalid request data.",
    already_requested:    "This item was already requested.",
    invalid_media_id:     "\u26A0\uFE0F Invalid media ID.",
    error_processing:     "\u26A0\uFE0F Error processing request.",
    request_success:      "\u2705 **{{title}}** has been requested!",
    label_genre:          "Genre",
    label_runtime:        "Runtime",
    label_rating:         "Rating",
    label_age_rating:     "Age Rating",
    label_content_rating: "Rated",
    label_providers:      "Also on",
    status_available:     "Available on Jellyfin",
    status_partial:       "Partially available",
    status_requested:     "Requested",
    similar_title:        "Similar Titles",
    similar_based_on:     "Similar to \"{{title}}\"",
    similar_not_found:    "Could not find this title on TMDB.",
    similar_no_results:   "No similar titles found for \"{{title}}\".",
    similar_error:        "Could not fetch similar titles. Please try again.",
    generic_error:        "Something went wrong. Please try again later.",
    no_description:       "No description available.",
    label_summary:        "Summary",
    label_directed_by:    "Directed by {{name}}",
    label_created_by:     "Created by {{name}}",
    movie_found:          "\uD83C\uDFAC Movie found:",
    tv_found:             "\uD83D\uDCFA TV show found:",
    and_connector:        "and",
    with_tag:             "with {{tags}} tag",
    with_tags:            "with {{tags}} tags",
    rate_limited:         "\u26A0\uFE0F You're using commands too fast. Please wait a moment.",
    btn_approve:          "\u2705 Approve",
    btn_decline:          "\u274C Decline",
    btn_approved_by:      "Approved by",
    btn_declined_by:      "Declined by",
    btn_already_handled:  "Already handled",
    admin_already_handled: "\u26A0\uFE0F This request has already been **{{status}}**{{handler}}. No action was taken.",
    admin_status_approved: "approved",
    admin_status_declined: "declined",
    admin_status_available: "marked as available",
    admin_status_other:    "handled",
    cleanup_title:         "\uD83D\uDDD1\uFE0F Cleanup Suggestions",
    cleanup_subtitle:      "These movies haven't been watched in a long time. Consider deleting them to free up storage.",
    cleanup_item_line:     "\u2022 {{title}} \u00B7 played {{plays}}\u00D7 \u00B7 last: {{last}} \u00B7 {{size}}",
    cleanup_never_played:  "never",
    cleanup_total_storage: "{{count}} item(s), {{size}} GB total",
    cleanup_no_candidates: "\u2705 No cleanup candidates found \u2014 your library is healthy.",
    cleanup_fetch_failed_title: "Cleanup Advisor \u2014 Fetch Failed",
    cleanup_fetch_failed:  "Could not fetch library data from Jellyfin: {{error}}",
    cleanup_fetch_failed_hint: "Try increasing **Cleanup Fetch Timeout** in the dashboard (Step 7). Recommended: 30s for ~500 titles, 60s for ~2000, 120s for ~6000.",
    foryou_title:               "\uD83C\uDFAF Recommendations for You",
    foryou_based_on_jellyfin:   "Based on your Jellyfin watch history",
    foryou_because_watched:     "Because you watched",
    foryou_no_history:          "\u274C You haven't watched anything on Jellyfin yet. Watch a few titles first!",
    foryou_no_recommendations:  "\u274C Couldn't find any recommendations. Watch a few more titles in Jellyfin.",
    foryou_no_library_matches:  "\u274C No matching titles in your library. Try the default filter to include items you can request.",
    foryou_no_jellyfin_user:    "\u26A0\uFE0F Your Discord account is not linked to a Jellyfin user. Ask an admin to set up your user mapping in Step 5.",
    foryou_legend:              "\u2705 = in library \u00B7 \u23F3 = requested \u00B7 \u26AA = not available",
    foryou_error:               "\u274C Could not fetch recommendations. Please try again.",
    // /help wizard
    wizard_title:               "\uD83D\uDCD6 Questorr \u2014 Command Help",
    wizard_footer:              "Click a button to run the command \u2014 or type the command yourself for advanced options.",
    wizard_section_quick:       "\uD83D\uDE80 Quick Actions",
    wizard_section_browse:      "\uD83D\uDCC2 Browse",
    wizard_section_search:      "\uD83D\uDD0D Search & Request",
    wizard_section_discover:    "\u2728 Discover",
    wizard_btn_foryou_all:      "For You",
    wizard_btn_foryou_avail:    "For You (Library)",
    wizard_btn_random_movie:    "Random Movie",
    wizard_btn_random_series:   "Random Series",
    wizard_btn_watchlist:       "Watchlist",
    wizard_btn_history:         "History",
    wizard_btn_upcoming:        "Upcoming",
    wizard_desc_foryou:         "Personalised recommendations from your Jellyfin watch history.",
    wizard_desc_random:         "Pick a random movie or series from your Jellyfin library.",
    wizard_desc_watchlist:      "View recent Seerr requests with status filters.",
    wizard_desc_history:        "What was recently added to Jellyfin.",
    wizard_desc_upcoming:       "Upcoming releases from TMDB.",
    wizard_desc_trending:       "Browse currently trending movies and TV shows.",
    wizard_desc_search:         "Find a title (you can request it later).",
    wizard_desc_request:        "Send an instant request for a title.",
    wizard_desc_status:         "Check the request status of a title in Seerr.",
    wizard_desc_recommend:      "Get TMDB recommendations based on a specific title.",
    wizard_desc_similar:        "Find similar titles by genre and keywords.",
    wizard_desc_collection:     "View all movies in a franchise.",
    wizard_desc_cast:           "Browse an actor's filmography.",
    wizard_desc_discover:       "Discover by genre, year, and rating.",
    wizard_btn_search:          "Search",
    wizard_btn_request:         "Request",
    wizard_btn_status:          "Status",
    wizard_btn_recommend:       "Recommend",
    wizard_btn_similar:         "Similar",
    wizard_btn_collection:      "Collection",
    wizard_btn_cast:            "Cast",
    wizard_modal_label_title:   "Title",
    wizard_modal_label_name:    "Name",
    wizard_modal_title_search:     "🔍 Search",
    wizard_modal_title_request:    "📥 Request",
    wizard_modal_title_recommend:  "⭐ Recommend",
    wizard_modal_title_similar:    "🔗 Similar Titles",
    wizard_modal_title_collection: "📦 Collection",
    wizard_modal_title_cast:       "🎭 Cast",
    wizard_modal_title_status:     "❓ Status",
    wizard_modal_ph_title:         "e.g. Pulp Fiction · Typos are ok!",
    wizard_modal_ph_name:          "e.g. Tom Hanks",
    dym_question:                  "Did you mean {{title}}?",
    dym_btn_no:                    "Other results",
    dym_alternatives:              "Here are other results — click to select:",
    dym_no_alternatives:           "⚠️ No alternative results found.",
    picker_recommend_pick:         "Pick a title to base recommendations on",
    picker_similar_pick:           "Pick a title to find similar ones",
    picker_collection_pick:        "Pick a movie to view its collection",
    picker_cast_pick:              "Pick an actor to view their filmography",
    picker_custom_input:           "Type a different title…",
    picker_custom_input_hint:      "Open a text input instead",
    picker_empty_state:            "No recent watch history found — type a title to continue.",
    action_btn_similar:            "Similar",
    action_btn_collection:         "Collection",
    action_btn_cast:               "Cast",
    action_btn_recommend:          "Recommend",
    action_cast_pick_intro:        "Pick a cast member from {{title}}:",
    action_cast_pick_placeholder:  "Choose an actor…",
    watchlist_title:       "\uD83D\uDCCB Request Watchlist",
    watchlist_empty:       "No requests found.",
    watchlist_no_mapping:  "\u26A0\uFE0F Your Discord account is not mapped to a Seerr user. Ask an admin to set up your user mapping.",
    watchlist_error:       "\u274C Could not fetch requests from Seerr.",
    watchlist_showing:     "Showing {{shown}} of {{total}} requests",
    watchlist_status_unknown:    "Unknown",
    watchlist_status_pending:    "Pending",
    watchlist_status_processing: "Processing",
    watchlist_status_partial:    "Partial",
    watchlist_status_available:  "Available",
    upcoming_title:        "\uD83D\uDCC5 Upcoming Releases",
    upcoming_empty:        "No upcoming releases found.",
    upcoming_error:        "\u274C Could not fetch upcoming releases from TMDB.",
    upcoming_page_of:      "Page {{current}} of {{total}}",
    history_title:         "\uD83D\uDCDA Recently Added",
    history_empty:         "No recently added content found on Jellyfin.",
    history_jf_missing:    "\u274C Jellyfin is not configured.",
    history_error:         "\u274C Could not fetch recently added content from Jellyfin.",
    history_added:         "Added",
    recommend_title:       "\uD83C\uDFAF Recommendations",
    recommend_based_on:    "Based on \"{{title}}\"",
    recommend_not_found:   "\u274C Could not find this title on TMDB.",
    recommend_no_similar:  "\u274C No recommendations found for \"{{title}}\".",
    recommend_error:       "\u274C Could not fetch recommendations. Please try again.",
    recommend_legend:      "\u2705 = In library \u00B7 \uD83D\uDD0D = Not yet available \u00B7 \uD83D\uDCE5 = Requested \u00B7 \u23F3 = Processing",
    btn_trailer:           "\u25B6 Trailer",
    discover_title:        "\uD83D\uDD0D Discover",
    discover_empty:        "\u274C No results found for your filters.",
    discover_error:        "\u274C Could not fetch results. Please try again.",
    discover_all:          "All",
    collection_title:      "\uD83D\uDCDA Collection",
    collection_not_found:  "\u274C Could not find this title on TMDB.",
    collection_movies_only:"\u26A0\uFE0F Collections are only available for movies.",
    collection_none:       "\u274C This movie is not part of a collection.",
    collection_error:      "\u274C Could not fetch collection. Please try again.",
    collection_available:  "in your library",
    cast_title:            "\uD83C\uDFAD Filmography",
    cast_name_required:    "\u26A0\uFE0F Please enter an actor or actress name.",
    cast_not_found:        "\u274C Could not find this person on TMDB.",
    cast_no_credits:       "\u274C No movie or TV credits found for this person.",
    cast_error:            "\u274C Could not fetch filmography. Please try again.",
    dm_pending_author:        "\u23F3 Request submitted",
    dm_pending_description:   "Your request for **{{title}}** has been submitted and will be reviewed by an admin shortly.",
    dm_approved_author:       "\u2705 Request approved",
    dm_approved_description:  "Your request for **{{title}}** has been **approved** by an admin. You will be notified as soon as it becomes available.",
    dm_auto_approved_author:  "\u26A1 Auto-approved",
    dm_auto_approved_description: "Your request for **{{title}}** was **auto-approved**. You will be notified as soon as it becomes available.",
    dm_declined_author:       "\u274C Request declined",
    dm_declined_description:  "Your request for **{{title}}** was **declined**.",
    dm_available_author:      "\uD83C\uDF89 Now available!",
    dm_available_description: "**{{title}}** is now available in Jellyfin. Enjoy!",
    dm_field_type:            "Type",
    dm_field_reason:          "Reason",
  },
  de: {
    event_pending:        "Neue Anfrage \u2013 Ausstehend",
    event_approved:       "Anfrage genehmigt",
    event_auto_approved:  "Anfrage automatisch genehmigt",
    event_available:      "Jetzt verf\u00FCgbar!",
    event_declined:       "Anfrage abgelehnt",
    event_failed:         "Download fehlgeschlagen",
    event_issue_created:  "Problem gemeldet",
    event_issue_comment:  "Problem-Kommentar",
    event_issue_resolved: "Problem gel\u00F6st",
    event_issue_reopened: "Problem wieder ge\u00F6ffnet",
    event_test:           "Test-Benachrichtigung",
    field_requested_by:   "Angefragt von",
    requested_by:         "Angefragt von {{user}}",
    field_type:           "Typ",
    field_type_movie:     "\uD83C\uDFAC Film",
    field_type_tv:        "\uD83D\uDCFA Serie",
    field_reason:         "Grund",
    field_rating:         "Bewertung",
    btn_view_seerr:       "In Seerr ansehen",
    btn_watch_now:        "\u25B6 Jetzt ansehen!",
    btn_imdb:             "IMDb",
    btn_letterboxd:       "Letterboxd",
    btn_request:          "\uD83D\uDCE5 Anfragen",
    btn_watch_now_short:  "\u25B6 Jetzt ansehen",
    daily_random_pick:    "Heutiger Zufallstitel",
    daily_recommendation: "\uD83C\uDFAC Heutige Empfehlung auf Jellyfin",
    status_unknown:       "Unbekannt",
    status_pending:       "Ausstehend",
    status_processing:    "Wird verarbeitet / heruntergeladen",
    status_partial:       "Teilweise verf\u00FCgbar",
    status_available:     "Verf\u00FCgbar",
    status_deleted:       "Gel\u00F6scht",
    status_pending_short: "Ausstehend",
    status_not_requested: "Dieser Titel wurde noch nicht angefragt.",
    successfully_requested: "\u2705 Erfolgreich angefragt!",
    requested_label:      "Angefragt",
    requested_all_seasons:"Alle Staffeln angefragt",
    requested_season:     "Staffel angefragt",
    requested_seasons:    "Staffeln angefragt",
    request_all_seasons:  "Alle Staffeln anfragen",
    request_season:       "Staffel anfragen",
    request_seasons:      "Staffeln anfragen",
    all_seasons:          "Alle Staffeln",
    season_label:         "Staffel",
    episodes_label:       "Episoden",
    stay_tuned:           "bleibt gespannt!",
    random_movie:         "Zuf\u00E4lliger Film",
    random_series:        "Zuf\u00E4llige Serie",
    title_invalid:        "\u26A0\uFE0F Der Titel scheint ung\u00FCltig zu sein.",
    content_already_available: "\u2705 Dieser Inhalt ist bereits in deiner Bibliothek verf\u00FCgbar!",
    error_occurred:       "\u26A0\uFE0F Ein Fehler ist aufgetreten.",
    error_seerr:          "\u26A0\uFE0F Seerr-Fehler: {{message}}",
    error_quota:          "\u26A0\uFE0F Anfrage fehlgeschlagen: M\u00F6glicherweise wurde dein Kontingent \u00FCberschritten oder dir fehlt die Berechtigung.",
    error_generic:        "\u26A0\uFE0F Fehler: {{message}}",
    error_request_failed: "\u26A0\uFE0F Die Anfrage konnte nicht gesendet werden.",
    error_season_select:  "\u26A0\uFE0F Fehler bei der Staffelauswahl.",
    error_tag_select:     "\u26A0\uFE0F Fehler beim Aktualisieren der Auswahl.",
    select_tags_placeholder: "Tags ausw\u00E4hlen (optional)",
    select_seasons_placeholder: "Staffeln zum Anfragen ausw\u00E4hlen...",
    status_disabled:      "\u26A0\uFE0F Der /status-Befehl ist derzeit deaktiviert.",
    status_select_title:  "\u274C Bitte w\u00E4hle einen Titel aus den Vorschl\u00E4gen.",
    status_seerr_missing: "\u274C Seerr ist nicht konfiguriert.",
    status_fetch_error:   "\u274C Status konnte nicht von Seerr abgerufen werden. Bitte versuche es erneut.",
    random_disabled:      "\u26A0\uFE0F Der /random-Befehl ist derzeit deaktiviert.",
    random_jf_missing:    "\u274C Jellyfin ist nicht konfiguriert.",
    random_not_found:     "\u274C Kein {{type}} in deiner Jellyfin-Bibliothek gefunden.",
    random_fetch_error:   "\u274C Zuf\u00E4lliger Titel konnte nicht abgerufen werden. Bitte versuche es erneut.",
    command_config_missing: "\u26A0\uFE0F Dieser Befehl ist deaktiviert, da die Seerr- oder TMDB-Konfiguration fehlt.",
    no_permission:        "\u274C Du hast keine Berechtigung, diesen Befehl zu verwenden.",
    id_invalid:           "\u26A0\uFE0F ID ung\u00FCltig.",
    invalid_selection:    "\u26A0\uFE0F Ung\u00FCltige Auswahl.",
    invalid_request:      "\u26A0\uFE0F Ung\u00FCltige Anfrage.",
    invalid_request_data: "\u26A0\uFE0F Ung\u00FCltige Anfragedaten.",
    already_requested:    "Dieser Titel wurde bereits angefragt.",
    invalid_media_id:     "\u26A0\uFE0F Ung\u00FCltige Medien-ID.",
    error_processing:     "\u26A0\uFE0F Fehler bei der Verarbeitung der Anfrage.",
    request_success:      "\u2705 **{{title}}** wurde angefragt!",
    label_genre:          "Genre",
    label_runtime:        "Laufzeit",
    label_rating:         "Bewertung",
    label_age_rating:     "Altersfreigabe",
    label_content_rating: "Freigabe",
    label_providers:      "Auch auf",
    status_available:     "Verf\u00FCgbar auf Jellyfin",
    status_partial:       "Teilweise verf\u00FCgbar",
    status_requested:     "Angefragt",
    similar_title:        "\u00C4hnliche Titel",
    similar_based_on:     "\u00C4hnlich wie \"{{title}}\"",
    similar_not_found:    "Dieser Titel konnte nicht auf TMDB gefunden werden.",
    similar_no_results:   "Keine \u00E4hnlichen Titel f\u00FCr \"{{title}}\" gefunden.",
    similar_error:        "\u00C4hnliche Titel konnten nicht abgerufen werden. Bitte versuche es erneut.",
    generic_error:        "Etwas ist schiefgelaufen. Bitte versuche es sp\u00E4ter erneut.",
    no_description:       "Keine Beschreibung verf\u00FCgbar.",
    label_summary:        "Zusammenfassung",
    label_directed_by:    "Regie: {{name}}",
    label_created_by:     "Erstellt von {{name}}",
    movie_found:          "\uD83C\uDFAC Film gefunden:",
    tv_found:             "\uD83D\uDCFA Serie gefunden:",
    and_connector:        "und",
    with_tag:             "mit Tag {{tags}}",
    with_tags:            "mit Tags {{tags}}",
    rate_limited:         "\u26A0\uFE0F Du verwendest Befehle zu schnell. Bitte warte einen Moment.",
    btn_approve:          "\u2705 Genehmigen",
    btn_decline:          "\u274C Ablehnen",
    btn_approved_by:      "Genehmigt von",
    btn_declined_by:      "Abgelehnt von",
    btn_already_handled:  "Bereits bearbeitet",
    admin_already_handled: "\u26A0\uFE0F Diese Anfrage wurde bereits **{{status}}**{{handler}}. Es wurde keine Aktion durchgef\u00FChrt.",
    admin_status_approved: "genehmigt",
    admin_status_declined: "abgelehnt",
    admin_status_available: "als verf\u00FCgbar markiert",
    admin_status_other:    "bearbeitet",
    cleanup_title:         "\uD83D\uDDD1\uFE0F Cleanup-Vorschl\u00E4ge",
    cleanup_subtitle:      "Diese Filme wurden seit langer Zeit nicht mehr angeschaut. Erw\u00E4ge sie zu l\u00F6schen, um Speicherplatz freizugeben.",
    cleanup_item_line:     "\u2022 {{title}} \u00B7 gespielt {{plays}}\u00D7 \u00B7 zuletzt: {{last}} \u00B7 {{size}}",
    cleanup_never_played:  "nie",
    cleanup_total_storage: "{{count}} Eintrag/Eintr\u00E4ge, {{size}} GB insgesamt",
    cleanup_no_candidates: "\u2705 Keine Cleanup-Kandidaten gefunden \u2014 deine Bibliothek ist gesund.",
    cleanup_fetch_failed_title: "Cleanup-Advisor \u2014 Abruf fehlgeschlagen",
    cleanup_fetch_failed:  "Konnte Bibliotheks-Daten von Jellyfin nicht abrufen: {{error}}",
    cleanup_fetch_failed_hint: "Erh\u00f6he **Cleanup-Abruf-Timeout** im Dashboard (Schritt 7). Empfohlen: 30s f\u00fcr ~500 Titel, 60s f\u00fcr ~2000, 120s f\u00fcr ~6000.",
    foryou_title:               "\uD83C\uDFAF Empfehlungen f\u00FCr dich",
    foryou_based_on_jellyfin:   "Basierend auf deiner Jellyfin-Watch-History",
    foryou_because_watched:     "Weil du geschaut hast:",
    foryou_no_history:          "\u274C Du hast in Jellyfin noch nichts angeschaut. Schau zuerst ein paar Titel!",
    foryou_no_recommendations:  "\u274C Keine Empfehlungen gefunden. Schau noch ein paar Titel in Jellyfin.",
    foryou_no_library_matches:  "\u274C Keine passenden Titel in deiner Bibliothek. Probiere den Standard-Filter, um Inhalte zum Anfragen zu sehen.",
    foryou_no_jellyfin_user:    "\u26A0\uFE0F Dein Discord-Konto ist keinem Jellyfin-Benutzer zugeordnet. Bitte einen Admin, dein Mapping in Schritt 5 einzurichten.",
    foryou_legend:              "\u2705 = in Bibliothek \u00B7 \u23F3 = angefragt \u00B7 \u26AA = nicht verf\u00FCgbar",
    foryou_error:               "\u274C Empfehlungen konnten nicht abgerufen werden. Bitte versuche es erneut.",
    // /help wizard
    wizard_title:               "\uD83D\uDCD6 Questorr \u2014 Befehls\u00FCbersicht",
    wizard_footer:              "Klicke einen Button, um den Befehl auszuf\u00FChren \u2014 oder tippe ihn f\u00FCr erweiterte Optionen.",
    wizard_section_quick:       "\uD83D\uDE80 Schnellaktionen",
    wizard_section_browse:      "\uD83D\uDCC2 St\u00F6bern",
    wizard_section_search:      "\uD83D\uDD0D Suchen & Anfragen",
    wizard_section_discover:    "\u2728 Entdecken",
    wizard_btn_foryou_all:      "F\u00FCr dich",
    wizard_btn_foryou_avail:    "F\u00FCr dich (Bibliothek)",
    wizard_btn_random_movie:    "Zufallsfilm",
    wizard_btn_random_series:   "Zufallsserie",
    wizard_btn_watchlist:       "Watchlist",
    wizard_btn_history:         "Verlauf",
    wizard_btn_upcoming:        "Demn\u00E4chst",
    wizard_desc_foryou:         "Personalisierte Empfehlungen aus deiner Jellyfin-Watch-History.",
    wizard_desc_random:         "Zuf\u00E4lliger Film oder Serie aus deiner Jellyfin-Bibliothek.",
    wizard_desc_watchlist:      "Aktuelle Seerr-Anfragen mit Status-Filtern.",
    wizard_desc_history:        "Was wurde k\u00FCrzlich zu Jellyfin hinzugef\u00FCgt?",
    wizard_desc_upcoming:       "Kommende Releases von TMDB.",
    wizard_desc_trending:       "Aktuelle Trends bei Filmen und Serien.",
    wizard_desc_search:         "Titel suchen (kann sp\u00E4ter angefragt werden).",
    wizard_desc_request:        "Direkte Anfrage f\u00FCr einen Titel senden.",
    wizard_desc_status:         "Status einer Anfrage in Seerr pr\u00FCfen.",
    wizard_desc_recommend:      "TMDB-Empfehlungen basierend auf einem bestimmten Titel.",
    wizard_desc_similar:        "\u00C4hnliche Titel nach Genre und Keywords finden.",
    wizard_desc_collection:     "Alle Filme einer Reihe anzeigen.",
    wizard_desc_cast:           "Filmografie eines Schauspielers durchst\u00F6bern.",
    wizard_desc_discover:       "Nach Genre, Jahr und Bewertung entdecken.",
    wizard_btn_search:          "Suche",
    wizard_btn_request:         "Anfragen",
    wizard_btn_status:          "Status",
    wizard_btn_recommend:       "Empfehlung",
    wizard_btn_similar:         "Ähnlich",
    wizard_btn_collection:      "Reihe",
    wizard_btn_cast:            "Cast",
    wizard_modal_label_title:   "Titel",
    wizard_modal_label_name:    "Name",
    wizard_modal_title_search:     "🔍 Suchen",
    wizard_modal_title_request:    "📥 Anfragen",
    wizard_modal_title_recommend:  "⭐ Empfehlung",
    wizard_modal_title_similar:    "🔗 Ähnliche Titel",
    wizard_modal_title_collection: "📦 Filmreihe",
    wizard_modal_title_cast:       "🎭 Cast",
    wizard_modal_title_status:     "❓ Status",
    wizard_modal_ph_title:         "z.B. Pulp Fiction · Tippfehler sind ok!",
    wizard_modal_ph_name:          "z.B. Tom Hanks",
    dym_question:                  "Meintest du {{title}}?",
    dym_btn_no:                    "Andere Ergebnisse",
    dym_alternatives:              "Hier sind andere Ergebnisse — klicke zum Auswählen:",
    dym_no_alternatives:           "⚠️ Keine alternativen Ergebnisse gefunden.",
    picker_recommend_pick:         "Wähle einen Titel als Empfehlungs-Basis",
    picker_similar_pick:           "Wähle einen Titel, um ähnliche zu finden",
    picker_collection_pick:        "Wähle einen Film, um seine Reihe zu sehen",
    picker_cast_pick:              "Wähle einen Schauspieler für seine Filmografie",
    picker_custom_input:           "Anderen Titel eingeben…",
    picker_custom_input_hint:      "Texteingabe öffnen",
    picker_empty_state:            "Keine Watch-History gefunden — gib einen Titel ein, um fortzufahren.",
    action_btn_similar:            "Ähnlich",
    action_btn_collection:         "Reihe",
    action_btn_cast:               "Cast",
    action_btn_recommend:          "Empfehlung",
    action_cast_pick_intro:        "Wähle einen Schauspieler aus {{title}}:",
    action_cast_pick_placeholder:  "Schauspieler auswählen…",
    watchlist_title:       "\uD83D\uDCCB Anfragen-Liste",
    watchlist_empty:       "Keine Anfragen gefunden.",
    watchlist_no_mapping:  "\u26A0\uFE0F Dein Discord-Konto ist keinem Seerr-Benutzer zugeordnet. Bitte einen Admin, dein User-Mapping einzurichten.",
    watchlist_error:       "\u274C Anfragen konnten nicht von Seerr abgerufen werden.",
    watchlist_showing:     "Zeige {{shown}} von {{total}} Anfragen",
    watchlist_status_unknown:    "Unbekannt",
    watchlist_status_pending:    "Ausstehend",
    watchlist_status_processing: "In Bearbeitung",
    watchlist_status_partial:    "Teilweise",
    watchlist_status_available:  "Verfügbar",
    upcoming_title:        "\uD83D\uDCC5 Kommende Ver\u00F6ffentlichungen",
    upcoming_empty:        "Keine kommenden Ver\u00F6ffentlichungen gefunden.",
    upcoming_error:        "\u274C Kommende Ver\u00F6ffentlichungen konnten nicht von TMDB abgerufen werden.",
    upcoming_page_of:      "Seite {{current}} von {{total}}",
    history_title:         "\uD83D\uDCDA Kürzlich hinzugefügt",
    history_empty:         "Keine kürzlich hinzugefügten Inhalte auf Jellyfin gefunden.",
    history_jf_missing:    "\u274C Jellyfin ist nicht konfiguriert.",
    history_error:         "\u274C Kürzlich hinzugefügte Inhalte konnten nicht von Jellyfin abgerufen werden.",
    history_added:         "Hinzugef\u00FCgt",
    recommend_title:       "\uD83C\uDFAF Empfehlungen",
    recommend_based_on:    "Basierend auf \"{{title}}\"",
    recommend_not_found:   "\u274C Dieser Titel konnte nicht auf TMDB gefunden werden.",
    recommend_no_similar:  "\u274C Keine Empfehlungen f\u00FCr \"{{title}}\" gefunden.",
    recommend_error:       "\u274C Empfehlungen konnten nicht abgerufen werden. Bitte versuche es erneut.",
    recommend_legend:      "\u2705 = In der Bibliothek \u00B7 \uD83D\uDD0D = Noch nicht verf\u00FCgbar \u00B7 \uD83D\uDCE5 = Angefragt \u00B7 \u23F3 = In Bearbeitung",
    btn_trailer:           "\u25B6 Trailer",
    discover_title:        "\uD83D\uDD0D Entdecken",
    discover_empty:        "\u274C Keine Ergebnisse f\u00FCr deine Filter gefunden.",
    discover_error:        "\u274C Ergebnisse konnten nicht abgerufen werden. Bitte versuche es erneut.",
    discover_all:          "Alle",
    collection_title:      "\uD83D\uDCDA Sammlung",
    collection_not_found:  "\u274C Dieser Titel konnte nicht auf TMDB gefunden werden.",
    collection_movies_only:"\u26A0\uFE0F Sammlungen sind nur f\u00FCr Filme verf\u00FCgbar.",
    collection_none:       "\u274C Dieser Film geh\u00F6rt zu keiner Sammlung.",
    collection_error:      "\u274C Sammlung konnte nicht abgerufen werden. Bitte versuche es erneut.",
    collection_available:  "in deiner Bibliothek",
    cast_title:            "\uD83C\uDFAD Filmografie",
    cast_name_required:    "\u26A0\uFE0F Bitte gib einen Schauspieler-Namen ein.",
    cast_not_found:        "\u274C Diese Person konnte nicht auf TMDB gefunden werden.",
    cast_no_credits:       "\u274C Keine Film- oder Serien-Credits f\u00FCr diese Person gefunden.",
    cast_error:            "\u274C Filmografie konnte nicht abgerufen werden. Bitte versuche es erneut.",
    dm_pending_author:        "\u23F3 Anfrage eingereicht",
    dm_pending_description:   "Deine Anfrage f\u00FCr **{{title}}** wurde erfolgreich eingereicht und wird in K\u00FCrze von einem Admin gepr\u00FCft.",
    dm_approved_author:       "\u2705 Anfrage genehmigt",
    dm_approved_description:  "Deine Anfrage f\u00FCr **{{title}}** wurde von einem Admin **genehmigt**. Du erh\u00E4ltst eine Nachricht, sobald deine Anfrage verf\u00FCgbar ist.",
    dm_auto_approved_author:  "\u26A1 Automatisch genehmigt",
    dm_auto_approved_description: "Deine Anfrage f\u00FCr **{{title}}** wurde **automatisch genehmigt**. Du erh\u00E4ltst eine Nachricht, sobald deine Anfrage verf\u00FCgbar ist.",
    dm_declined_author:       "\u274C Anfrage abgelehnt",
    dm_declined_description:  "Deine Anfrage f\u00FCr **{{title}}** wurde **abgelehnt**.",
    dm_available_author:      "\uD83C\uDF89 Jetzt verf\u00FCgbar!",
    dm_available_description: "**{{title}}** ist ab sofort in Jellyfin verf\u00FCgbar. Viel Spa\u00DF beim Schauen!",
    dm_field_type:            "Typ",
    dm_field_reason:          "Begr\u00FCndung",
  },
};

export function t(key, vars) {
  const lang = (process.env.BOT_LANGUAGE || "en").toLowerCase();
  const dict = strings[lang] || strings["en"];
  let str = dict[key] ?? strings["en"][key] ?? key;
  if (vars && typeof str === "string") {
    for (const [k, v] of Object.entries(vars)) {
      str = str.replace(new RegExp(`\\{\\{\\s*${k}\\s*\\}\\}`, "g"), String(v));
    }
  }
  return str;
}

export function tNotif(key, envKey) {
  const custom = process.env[envKey];
  if (custom && custom.trim()) return custom.trim();
  return t(key);
}

export default { t, tNotif };
